language: r
sudo: required
dist: trusty
bioc_required: true
cache: packages
addons:
  apt:
    packages:
      - libgsl-dev
      - libsdl1.2-dev
install:
  - R -e 'devtools::install_deps(upgrade = T, dependencies = c("Depends", "Imports", "LinkingTo", "Suggests", "Enhances"))'
  - R -e 'devtools::install()'
  - R -e 'dyneval::check_dependencies()'
