language: r
sudo: required
dist: trusty
bioc_required: true
cache: packages
addons:
  apt:
    packages:
      - libgsl-dev
      - libsdl1.2-dev
install:
  - R -e 'devtools::install(dependencies = T, upgrade_dependencies = T)'
  - R -e 'library(dyneval); dyneval::check_dependencies()'
