language: r
sudo: required
dist: trusty
bioc_required: true
cache: packages
warnings_are_errors: true
addons:
  apt:
    packages:
      - libgsl-dev
      - libsdl1.2-dev
before_script:
  - R -e 'devtools::install_deps(dependencies = T, upgrade = T)'
  - R -e 'library(dyneval); dyneval::check_dependencies()'
