#!/bin/bash
module load python/x86_64/3.5.1
virtualenv -p python3 $1/gpfates --system-site-packages
cd $1/gpfates
source bin/activate
pip install numpy pandas matplotlib tqdm GPy
pip install git+https://github.com/SheffieldML/GPclust.git
pip install git+https://github.com/Teichlab/GPfates.git@bccd5496b4121b3e634ce7cd5b0bff823b2850fa
