#!/bin/bash
install_dir="$1"
if [ ! -d $install_dir ]; then
  mkdir $install_dir
  module load python/x86_64/3.5.1
  virtualenv -p python3 $install_dir --system-site-packages
  cd $install_dir
  source bin/activate
  pip install numpy pandas matplotlib tqdm
  pip install GPy
  pip install git+https://github.com/SheffieldML/GPclust.git
  pip install git+https://github.com/Teichlab/GPfates.git@bccd5496b4121b3e634ce7cd5b0bff823b2850fa
fi
