check_dimred <- function(object, insert_phantom_edges) {
  if (is_ti_wrapper(object)) {
    dimred_object <- dimred_trajectory(object, insert_phantom_edges = insert_phantom_edges)
  } else if (is_ti_dimred_wrapper(object)) {
    dimred_object <- object
  } else {
    stop(sQuote("object"), " is not an object as generated by plot_default, wrap_ti_task_data or wrap_ti_prediction.")
  }
  dimred_object
}


#' Perform dimensionality reduction on a trajectory and the respective samples in order to plot it
#'
#' @param traj_object A trajectory as generated by
#'  \code{\link{wrap_ti_task_data}} or
#'  \code{\link{wrap_ti_prediction}}
#' @param insert_phantom_edges attempt to plot bifurcating edges correctly automatically
#'
#' @importFrom igraph graph_from_data_frame layout_with_kk E
#' @importFrom RColorBrewer brewer.pal
#' @importFrom grDevices col2rgb rainbow rgb
#'
#' @export
dimred_trajectory <- function(traj_object, insert_phantom_edges = T) {
  #name <- paste0(traj_object$type, "/", traj_object$ti_type, "/", traj_object$name)
  name <- traj_object$id

  # retrieve some objects to work with
  cell_ids <- traj_object$cell_ids
  milestone_ids <- traj_object$milestone_ids
  num_milestones <- length(milestone_ids)
  milestone_network <- traj_object$milestone_network
  milestone_percentages <- traj_object$milestone_percentages

  # determine colours associated with each milestone
  col_milest_hex <-
    if (length(milestone_ids) <= 12) {
      RColorBrewer::brewer.pal(max(3, num_milestones), "Set3")[seq_len(num_milestones)]
    } else {
      sample(rainbow(num_milestones))
    }
  col_milest_rgb <- t(col2rgb(col_milest_hex))
  rownames(col_milest_rgb) <- names(col_milest_hex) <- milestone_ids

  # determine colour for sample by mixing milestone colours
  mix_colours <- function(milid, milpct) {
    colour_rgb <- apply(col_milest_rgb[milid,,drop=F], 2, function(x) sum(x * milpct))
    do.call(rgb, as.list(c(colour_rgb, maxColorValue = 256)))
  }
  colours_samples <-
    milestone_percentages %>%
    group_by(cell_id) %>%
    summarise(colour = mix_colours(milestone_id, percentage)) %$%
    setNames(colour, cell_id)

  # add phantom links, ifneedbe
  if (insert_phantom_edges) {
    structure <- add_phantom_edges(milestone_ids, milestone_network)
  } else {
    structure <- milestone_network
  }

  # adjust weights on structure to make it easier to plot
  if (min(structure$length) * 3 < max(structure$length)) {
    structure <- structure %>% mutate(
      length = sqrt((length - min(length)) / (max(length) - min(length)) + .5)
    )
  }

  # reduce dimensionality on milestone_network
  gr <- graph_from_data_frame(structure %>% rename(weight = length), vertices = milestone_ids)
  space_milest_m <- layout_with_kk(gr, maxiter = 200) %>% scale_uniformily()
  dimnames(space_milest_m) <- list(milestone_ids, paste0("Comp", seq_len(ncol(space_milest_m))))

  # project dimensionality to samples
  mix_dimred <- function(milid, milpct) {
    apply(space_milest_m[milid,,drop=F], 2, function(x) sum(x * milpct)) %>% t %>% as_data_frame
  }
  space_samples <-
    milestone_percentages %>%
    group_by(cell_id) %>%
    do(mix_dimred(.$milestone_id, .$percentage)) %>%
    ungroup %>%
    slice(match(cell_ids, cell_id))

  # format data
  space_milestones <- data.frame(
    name,
    milestone_id = milestone_ids,
    space_milest_m[milestone_ids,],
    colour = col_milest_hex[milestone_ids],
    stringsAsFactors = F)

  space_lines <- data.frame(
    name,
    from = milestone_network$from,
    from = space_milest_m[milestone_network$from,,drop=F],
    to = milestone_network$to,
    to = space_milest_m[milestone_network$to,,drop=F],
    row.names = NULL,
    stringsAsFactors = F)

  space_samples <- data.frame(
    name,
    space_samples,
    colour = colours_samples[space_samples$cell_id],
    stringsAsFactors = F)

  l <- lst(
    space_milestones = space_milestones,
    space_lines = space_lines,
    space_samples = space_samples
  )
  class(l) <- c("dyneval::ti_dimred_wrapper", "list")
  l
}

is_ti_dimred_wrapper <- function(object) {
  "dyneval::ti_dimred_wrapper" %in% class(object)
}
