#' Plot a dimensionality reduced trajectory
#'
#' @param object output as generated by \code{\link{dimred_trajectory}}, \code{\link{wrap_ti_task_data}} or \code{\link{wrap_ti_prediction}}
#' @param insert_phantom_edges attempt to plot bifurcating edges correctly automatically
#'
#' @import ggplot2
#' @importFrom grid arrow
#'
#' @export
plot_default <- function(object, insert_phantom_edges = T) {
  if (is_ti_wrapper(object)) {
    dimred_object <- dimred_trajectory(object, insert_phantom_edges = insert_phantom_edges)
  } else if (is_ti_dimred_wrapper(object)) {
    dimred_object <- object
  } else {
    stop(sQuote("object"), " is not an object as generated by plotLearnerData.ti.default, wrap_ti_task_data or wrap_ti_prediction.")
  }
  with(dimred_object, {
    ggplot() +
      geom_segment(aes(x = from.Comp1, xend = to.Comp1, y = from.Comp2, yend = to.Comp2), space_lines,
                   size = 10, colour = "#444444", arrow = arrow(length = unit(.5, "cm"), type="closed")) +
      geom_point(aes(Comp1, Comp2, colour = colour), space_samples, size = 3) +
      geom_point(aes(Comp1, Comp2, colour = colour, fill = colour), space_milestones, size = 5, shape = 4, stroke = 2) +
      geom_text(aes(Comp1, Comp2, label = id), space_milestones, nudge_y = .05) +
      scale_colour_identity() +
      scale_fill_identity() +
      scale_x_continuous(limits = c(-.55, .55)) +
      scale_y_continuous(limits = c(-.55, .55)) +
      coord_equal() +
      labs(x = "Component 1", y = "Component 2")
  })
}

#' Plot a dimensionality reduced trajectory
#'
#' @param original_object output as generated by \code{\link{dimred_trajectory}}, \code{\link{wrap_ti_task_data}} or \code{\link{wrap_ti_prediction}}
#' @param new_object output as generated by \code{\link{dimred_trajectory}}, \code{\link{wrap_ti_task_data}} or \code{\link{wrap_ti_prediction}}
#' @param insert_phantom_edges attempt to plot bifurcating edges correctly automatically
#'
#' @import ggplot2
#' @importFrom grid arrow
#'
#' @export
plot_combined <- function(original_object, new_object, insert_phantom_edges = T) {
  if (is_ti_wrapper(original_object)) {
    original_dimred <- dimred_trajectory(original_object, insert_phantom_edges = insert_phantom_edges)
  } else if (is_ti_dimred_wrapper(original_object)) {
    original_dimred <- original_object
  } else {
    stop(sQuote("original_object"), " is not an object as generated by plotLearnerData.ti.default, wrap_ti_task_data or wrap_ti_prediction.")
  }

  if (is_ti_wrapper(new_object)) {
    new_dimred <- dimred_trajectory(new_object, insert_phantom_edges = insert_phantom_edges)
  } else if (is_ti_dimred_wrapper(new_object)) {
    new_dimred <- new_object
  } else {
    stop(sQuote("new_object"), " is not an object as generated by plotLearnerData.ti.default, wrap_ti_task_data or wrap_ti_prediction.")
  }

  combined_dimred <- new_dimred
  combined_dimred$space_samples$colour <- original_dimred$space_samples$colour

  with(combined_dimred, {
    ggplot() +
      geom_segment(aes(x = from.Comp1, xend = to.Comp1, y = from.Comp2, yend = to.Comp2), space_lines,
                   size = 10, colour = "#444444", arrow = arrow(length = unit(.5, "cm"), type="closed")) +
      geom_point(aes(Comp1, Comp2, colour = colour), space_samples, size = 3, alpha = .5) +
      scale_colour_identity() +
      scale_fill_identity() +
      scale_x_continuous(limits = c(-.55, .55)) +
      scale_y_continuous(limits = c(-.55, .55)) +
      coord_equal() +
      labs(x = "Component 1", y = "Component 2")
  })
}


#' Plot the Earth Mover's distances in a heatmap
#'
#' @param traj the trajectory (less than 500 cells is recommended)
#' @param emdist the Earth Mover's distances as calculated by \link{\code{emdist}}
#' @param dimred the dimensionality reduction of the trajectory as produced by \code{\link{dimred_trajectory}}
#' @export
#'
#' @importFrom reshape2 acast
#' @importFrom pheatmap pheatmap
plot_emdist <- function(traj, dist, dimred = NULL, ...) {
  milestone_percentages <- traj$milestone_percentages
  pct <- as.data.frame(milestone_percentages[,-1])
  rownames(pct) <- milestone_percentages$id

  if (is.null(dimred)) {
    dimred <- dimred_trajectory(traj)
  }

  ann_colours <- setNames(lapply(dimred$milestone_states$colour, function(x) c("white", x)), dimred$milestone_states$id)

  pheatmap::pheatmap(
    dist,
    cluster_rows = F,
    cluster_cols = F,
    annotation_col = pct,
    annotation_row = pct,
    annotation_colors = ann_colours,
    legend = F,
    legend_labels = F,
    legend_breaks = F,
    border_color = NA,
    show_rownames = F,
    show_colnames = F,
    annotation_legend = F,
    annotation_names_row = F,
    annotation_names_col = F,
    fontsize = 20 / length(traj$milestone_ids),
    ...)
}
