#' Plot a dimensionality reduced trajectory
#'
#' @param object output as generated by \code{\link{dimred_trajectory}}, \code{\link{wrap_ti_task_data}} or \code{\link{wrap_ti_prediction}}
#' @param insert_phantom_edges attempt to plot bifurcating edges correctly automatically
#'
#' @import ggplot2
#' @importFrom grid arrow
#' @importFrom cowplot theme_cowplot
#'
#' @export
plot_default <- function(object, insert_phantom_edges = TRUE) {
  dimred_object <- check_or_perform_dimred(object, insert_phantom_edges)

  with(dimred_object, {
    segment_aes <- aes(x = from.Comp1, xend = to.Comp1, y = from.Comp2, yend = to.Comp2)
    ggplot() +
      geom_segment(segment_aes, size = 10, colour = "#444444",
                   space_lines %>% filter(directed),
                   arrow = arrow(length = unit(.5, "cm"), type="closed")) +
      geom_segment(segment_aes, size = 10, colour = "#444444", space_lines %>% filter(!directed)) +
      geom_point(aes(Comp1, Comp2, colour = colour), space_samples, size = 3) +
      geom_point(aes(Comp1, Comp2, colour = colour, fill = colour), space_milestones, size = 5, shape = 4, stroke = 2) +
      geom_text(aes(Comp1, Comp2, label = milestone_id), space_milestones, nudge_y = .05) +
      scale_colour_identity() +
      scale_fill_identity() +
      scale_x_continuous(limits = c(-.55, .55)) +
      scale_y_continuous(limits = c(-.55, .55)) +
      coord_equal() +
      labs(x = "Component 1", y = "Component 2") +
      cowplot::theme_cowplot()
  })
}

#' Plot a dimensionality reduced trajectory
#'
#' @param original_object output as generated by \code{\link{dimred_trajectory}}, \code{\link{wrap_ti_task_data}} or \code{\link{wrap_ti_prediction}}
#' @param new_object output as generated by \code{\link{dimred_trajectory}}, \code{\link{wrap_ti_task_data}} or \code{\link{wrap_ti_prediction}}
#' @param insert_phantom_edges attempt to plot bifurcating edges correctly automatically
#'
#' @import ggplot2
#' @importFrom grid arrow
#' @importFrom cowplot theme_cowplot
#'
#' @export
plot_combined <- function(original_object, new_object, insert_phantom_edges = TRUE) {
  original_dimred <- check_or_perform_dimred(original_object, insert_phantom_edges)
  new_dimred <- check_or_perform_dimred(new_object, insert_phantom_edges)

  combined_dimred <- new_dimred
  combined_dimred$space_samples$colour <- original_dimred$space_samples$colour

  with(combined_dimred, {
    ggplot() +
      geom_segment(aes(x = from.Comp1, xend = to.Comp1, y = from.Comp2, yend = to.Comp2), space_lines,
                   size = 10, colour = "#444444", arrow = arrow(length = unit(.5, "cm"), type="closed")) +
      geom_point(aes(Comp1, Comp2, colour = colour), space_samples, size = 3, alpha = .5) +
      scale_colour_identity() +
      scale_fill_identity() +
      scale_x_continuous(limits = c(-.55, .55)) +
      scale_y_continuous(limits = c(-.55, .55)) +
      coord_equal() +
      labs(x = "Component 1", y = "Component 2") +
      cowplot::theme_cowplot()
  })
}


#' Plot the Earth Mover's distances in a heatmap
#'
#' @param traj the trajectory (less than 500 cells is recommended)
#' @param dist the Earth Mover's distances as calculated by \code{\link{compute_emlike_dist}}
#' @param dimred the dimensionality reduction of the trajectory as produced by \code{\link{dimred_trajectory}}
#' @param ... extra parameters to be passed to \code{\link[pheatmap]{pheatmap}}
#' @export
#'
#' @importFrom reshape2 acast
#' @importFrom pheatmap pheatmap
plot_emdist <- function(traj, dist, dimred = NULL, ...) {
  pct <- traj$milestone_percentages %>%
    reshape2::acast(cell_id ~ milestone_id, value.var = "percentage", fill = 0) %>%
    as.data.frame(check.names = FALSE)

  if (is.null(dimred)) {
    dimred <- dimred_trajectory(traj)
  }

  ann_colours <- setNames(lapply(dimred$milestone_states$colour, function(x) c("white", x)), dimred$milestone_states$milestone_id)

  pheatmap::pheatmap(
    dist,
    cluster_rows = TRUE,
    cluster_cols = TRUE,
    annotation_col = pct,
    annotation_row = pct,
    annotation_colors = ann_colours,
    legend = FALSE,
    legend_labels = FALSE,
    legend_breaks = FALSE,
    border_color = NA,
    show_rownames = FALSE,
    show_colnames = FALSE,
    annotation_legend = FALSE,
    annotation_names_row = FALSE,
    annotation_names_col = FALSE,
    fontsize = 20 / length(traj$milestone_ids),
    ...
  )
}
