#' Perform dimensionality reduction on a trajectory and the respective samples in order to plot it
#'
#' @param traj_object A trajectory as generated by \link{\code{wrap_ti_task_data}} or
#'  \link{\code{wrap_ti_prediction}}
#' @param insert_phantom_edges attempt to plot bifurcating edges correctly automatically
#'
#' @import dplyr
#' @importFrom igraph graph_from_data_frame layout_with_kk E
#' @importFrom SCORPIUS rescale.and.center
#' @importFrom RColorBrewer brewer.pal
#'
#' @export
plotLearnerData.ti.default <- function(traj_object, insert_phantom_edges = T) {
  name <- paste0(traj_object$type, "/", traj_object$ti_type, "/", traj_object$name)

  # retrieve information on states
  state_names <- traj_object$state_names
  if (length(state_names) <= 12) {
    colour_states <- RColorBrewer::brewer.pal(max(3, length(state_names)), "Set3")[seq_along(state_names)]
    colours_states <- setNames(colour_states, state_names)
  } else {
    colours_states <- setNames(sample(rainbow(length(state_names))), state_names)
  }
  colours_rgb_states <- t(col2rgb(colours_states))

  # get state_network
  state_network <- traj_object$state_network

  # retrieve information on samples
  state_percentages <- traj_object$state_percentages
  state_percentages_m <- as.matrix(state_percentages[,state_names,drop=F])
  rownames(state_percentages_m) <- state_percentages$id
  colours_rgb_samples <- state_percentages_m %*% colours_rgb_states
  colours_samples <- mapply(colours_rgb_samples[,1], colours_rgb_samples[,2], colours_rgb_samples[,3], FUN = rgb, maxColorValue = 256)

  # add imaginary links, ifneedbe
  if (insert_phantom_edges) {
    structure <- bind_rows(
      state_network,
      bind_rows(lapply(state_names, function(x) {
        strx <- state_network %>%
          filter(from == x)

        if (nrow(strx) > 1) {
          strx <- strx %>%
            mutate(
              angle = seq(0, 120/360*pi*2, length.out = n()),
              x = length * cos(angle),
              y = length * sin(angle)
            )
          poss <- strx %>% select(x, y) %>% as.matrix
          rownames(poss) <- strx$to
          poss %>%
            dist %>%
            as.matrix %>%
            reshape2::melt(varnames = c("from", "to"), value.name = "length") %>%
            mutate(from = as.character(from), to = as.character(to)) %>%
            filter(from != to)
        } else {
          NULL
        }
      })),
      bind_rows(lapply(state_names, function(x) {
        strx <- state_network %>%
          filter(to == x)

        if (nrow(strx) > 1) {
          strx <- strx %>%
            mutate(
              angle = seq(0, 120/360*pi*2, length.out = n()),
              x = length * cos(angle),
              y = length * sin(angle)
            )
          poss <- strx %>% select(x, y) %>% as.matrix
          rownames(poss) <- strx$from
          poss %>%
            dist %>%
            as.matrix %>%
            reshape2::melt(varnames = c("from", "to"), value.name = "length") %>%
            mutate(from = as.character(from), to = as.character(to)) %>%
            filter(from != to)
        } else {
          NULL
        }
      })))
  } else {
    structure <- state_network
  }

  # reduce dimensionality on state_network
  gr <- graph_from_data_frame(structure, vertices = state_names)
  lengths <- E(gr)$length
  if (min(lengths) * 3 < max(lengths)) {
    lengths <- ((lengths - min(lengths)) / (max(lengths) - min(lengths)) + .5) %>% sqrt
  }

  gr_space_states <- layout_with_kk(gr, weights = lengths, maxiter = 200) %>% SCORPIUS::rescale.and.center()
  dimnames(gr_space_states) <- list(state_names, paste0("Comp", seq_len(ncol(gr_space_states))))

  # project dimensionality to samples
  gr_space_samples <- state_percentages_m %*% gr_space_states

  # format data
  space_states <- data.frame(
    name,
    id = state_names,
    gr_space_states,
    colour = colours_states,
    stringsAsFactors = F)
  space_lines <- data.frame(
    name,
    from = gr_space_states[state_network$from,,drop=F],
    to = gr_space_states[state_network$to,,drop=F],
    row.names = NULL,
    stringsAsFactors = F)
  space_samples <- data.frame(
    name,
    id = state_percentages$id,
    gr_space_samples,
    colour = colours_samples,
    stringsAsFactors = F)

  l <- list(
    space_states = space_states,
    space_lines = space_lines,
    space_samples = space_samples
  )
  class(l) <- "dyneval::ti_dimred_wrapper"
  l
}

is_ti_dimred_wrapper <- function(object) {
  class(object) == "dyneval::ti_dimred_wrapper"
}

#' Plot a dimensionality reduced trajectory
#'
#' @param object output as generated by \code{plotLearnerData.ti.default}, \link{\code{wrap_ti_task_data}} or \link{\code{wrap_ti_prediction}}
#' @param insert_phantom_edges attempt to plot bifurcating edges correctly automatically
#'
#' @import ggplot2
#' @importFrom grid arrow
#'
#' @export
plotLearner.ti.default <- function(object, insert_phantom_edges = T) {
  if (is_ti_wrapper(object)) {
    dimred_object <- plotLearnerData.ti.default(object, insert_phantom_edges = insert_phantom_edges)
  } else if (is_ti_dimred_wrapper(object)) {
    dimred_object <- object
  } else {
    stop(sQuote("object"), " is not an object as generated by plotLearnerData.ti.default, wrap_ti_task_data or wrap_ti_prediction.")
  }
  with(dimred_object, {
    ggplot() +
      geom_segment(aes(x = from.Comp1, xend = to.Comp1, y = from.Comp2, yend = to.Comp2), space_lines,
                   size = 10, colour = "#444444", arrow = arrow(length = unit(.5, "cm"), type="closed")) +
      geom_point(aes(Comp1, Comp2, colour = colour), space_samples, size = 3) +
      geom_point(aes(Comp1, Comp2, colour = colour, fill = colour), space_states, size = 5, shape = 4, stroke = 2) +
      geom_text(aes(Comp1, Comp2, label = id), space_states, nudge_y = .05) +
      scale_colour_identity() +
      scale_fill_identity() +
      scale_x_continuous(limits = c(-.55, .55)) +
      scale_y_continuous(limits = c(-.55, .55)) +
      coord_equal() +
      labs(x = "Component 1", y = "Component 2")
  })
}
